### ISSUE TITLE
Kedroviz not rendering pipeline

### ISSUE THREAD

**Issue by Wilsven** [Synapxe-DNA/healthhub-content-optimization#202]
## Description

The Github page deployed on the repository for the Kedroviz visualization isn’t displaying the `azure_rag` pipeline. Could  please look into this?

## Steps to Reproduce

1. You may head to the repository and click on the link to the deployed Github pages on the left-hand panel
2. Alternatively, you may head to `Actions` > `Publish and share Kedro Viz` > Select any actions
3. Select `deploy` > Expand `Deploy Kedro-Viz to GH Pages` > Scroll down and you will find that `azure_rag` is not included

![image.png](https://huly.app/files?workspace=w-wilsvenleong-dataanalytic-6703ed3e-1f50d32b59-da5fb1&file=3d60c32a-35ae-40e5-b9af-bde31612da59&width=1072 "image.png")\
![image.png](https://huly.app/files?workspace=w-wilsvenleong-dataanalytic-6703ed3e-1f50d32b59-da5fb1&file=2c650c12-0b56-4a62-b54c-1b963addf8b6&width=974 "image.png")

<sub><a href="https://huly.app/guest/dataanalyticsai-6703ed3e-1f50d32b59-da5fb2?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA0YzM0MWI5ODBmNDFkYjY2ZjNhYjAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctd2lsc3Zlbmxlb25nLWRhdGFhbmFseXRpYy02NzAzZWQzZS0xZjUwZDMyYjU5LWRhNWZiMSJ9.pTVjyng276GkHHTkWhHif6kgPHEGDqHO-Il0Kf-ILRY">Huly&reg;: <b>CONTE-203</b></a></sub>

**Comment by yadanaraung27** [comment]
I have looked into this bug. The issue is due to the `credentials.yml` file under `content-optimization\conf\local\`. 

This `credentials.yml` file is used in the `azure_rag` pipeline. This file is created locally, and is not pushed to GitHub due to it containing credentials, hence it is `.gitkeep` under `content-optimization\conf\local\`. 

Therefore, when `kedro viz` is ran locally, it is able to display all pipelines including `azure_rag` pipeline. 

However, since `credentials.yml` is not pushed to GitHub, thus in the Deployed GitHub Page for the kedro visualization, it will show only the three pipelines without the `azure_rag` pipeline.

To resolve this issue, I have adjusted the file `llm_extraction.py` that interacts with the `credentials.yml`. For more details of the changes made, I will be creating a PR, please do read the description to understand the changes. Thank you!
